FROM node:lts-alpine3.12

RUN apk add --no-cache tzdata

WORKDIR /usr/app

EXPOSE 4000

RUN mkdir api
WORKDIR ./api

ADD api/package.json package.json
ADD api/yarn.lock yarn.lock

RUN yarn

ARG api_tz
ENV TZ ${api_tz}

ENTRYPOINT ["yarn", "watch"]
