version: "3.7"

services:
  api:
    build:
      args:
        api_tz: ${API_TZ}
      context: ..
      dockerfile: docker/Dockerfile-api-dev
    networks:
      - health-dashboard-network
    ports:
      - "4000:4000"
    volumes:
      - health-user-data:/usr/data:ro
      - ../api/src:/usr/app/api/src
    environment:
      API_LOG_LEVEL: debug

  git-sync:
    image: k8s.gcr.io/git-sync:v3.1.6
    volumes:
      - health-user-data:/tmp:rw
    environment:
      GIT_SYNC_USERNAME: ${GIT_SYNC_USERNAME}
      GIT_SYNC_PASSWORD: ${GIT_SYNC_PASSWORD}
      GIT_SYNC_REPO: ${GIT_SYNC_REPO}
      GIT_SYNC_DEST: health-data
      GIT_SYNC_WAIT: 10

  grafana:
    image: grafana/grafana:7.1.5
    networks:
      - health-dashboard-network
    ports:
      - "3000:3000"
    volumes:
      - health-grafana-data-dev:/var/lib/grafana:rw
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_INSTALL_PLUGINS: simpod-json-datasource

networks:
  health-dashboard-network:
    driver: bridge

volumes:
  health-user-data:
  health-grafana-data-dev:
