FROM curlimages/curl:7.69.1

# see https://github.com/eficode/wait-for, https://docs.docker.com/compose/startup-order/
ADD docker/grafana-setup/wait-for.sh wait-for.sh
ADD docker/grafana-setup/setup.sh setup.sh

ARG data_path
ADD ${data_path}/dashboards dashboards

ENTRYPOINT ["./wait-for.sh", "grafana:3000", "--", "./setup.sh"]
