version: "3.7"

services:
  api:
    build:
      args:
        api_tz: ${API_TZ}
      context: ..
      dockerfile: docker/Dockerfile-api-dev
    networks:
      - health-dashboard-network
    ports:
      - "4000:4000"
    volumes:
      - type: bind
        source: ../api/src
        target: /usr/app/api/src
      - type: bind
        source: ../${DATA_PATH:-data}
        target: /usr/app/data
    environment:
      API_LOG_LEVEL: debug

  grafana:
    image: grafana/grafana:7.1.5
    networks:
      - health-dashboard-network
    ports:
      - "3000:3000"
    volumes:
      - type: volume
        source: health-grafana-data-dev
        target: /var/lib/grafana
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_INSTALL_PLUGINS: simpod-json-datasource

networks:
  health-dashboard-network:
    driver: bridge

volumes:
  health-grafana-data-dev:
