FROM node:13.13.0-alpine3.10

RUN apk add --no-cache tzdata

WORKDIR /usr/app

EXPOSE 4000

RUN mkdir api
WORKDIR ./api

ADD api/package.json package.json
ADD api/yarn.lock yarn.lock

RUN yarn

ARG api_tz
ENV TZ ${api_tz}

ARG data_path
ADD ${data_path} ../data
ENV DATA_PATH data

ADD api/src src

ENTRYPOINT ["yarn", "start"]
