version: "3.7"

services:
  api:
    build:
      args:
        api_tz: ${API_TZ}
        data_path: ${DATA_PATH:-data}
      context: ..
      dockerfile: docker/Dockerfile-api
    networks:
      - health-dashboard-network
    ports:
      - "4000:4000"

  grafana:
    build:
      context: ..
      dockerfile: docker/Dockerfile-grafana
    depends_on:
      - api
    networks:
      - health-dashboard-network
    ports:
      - "3000:3000"
    volumes:
      - type: volume
        source: health-grafana-data
        target: /var/lib/grafana
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin

  grafana-setup:
    build:
      args:
        data_path: ${DATA_PATH:-data}
      context: ..
      dockerfile: docker/Dockerfile-grafana-setup
    depends_on:
      - grafana
    networks:
      - health-dashboard-network

networks:
  health-dashboard-network:
    driver: bridge

volumes:
  health-grafana-data:
