version: "3.7"

services:
  api:
    build:
      args:
        api_tz: ${API_TZ}
        data_path: ${DATA_PATH:-data}
      context: ..
      dockerfile: docker/Dockerfile-api
    networks:
      - health-dashboard-network
    ports:
      - "12001:4000"

  grafana:
    image: grafana/grafana:7.1.5
    networks:
      - health-dashboard-network
    ports:
      - "12000:3000"
    volumes:
      - type: volume
        source: health-grafana-data
        target: /var/lib/grafana
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_INSTALL_PLUGINS: simpod-json-datasource

networks:
  health-dashboard-network:
    driver: bridge

volumes:
  health-grafana-data:
