FROM node:13.13.0-alpine3.10

WORKDIR /usr/app

EXPOSE 4000

RUN mkdir api
WORKDIR ./api

ADD api/package.json package.json
ADD api/yarn.lock yarn.lock

RUN yarn

ARG api_data_path
ADD ${api_data_path} ../data
ENV API_DATA_PATH data

ADD api/src src

ENTRYPOINT ["yarn", "start"]
