FROM node:13.13.0-alpine3.10

RUN apk add --no-cache tzdata

WORKDIR /usr/app

EXPOSE 4000

RUN mkdir api
WORKDIR ./api

ADD api/package.json package.json
ADD api/yarn.lock yarn.lock

RUN yarn

ENV DATA_PATH data

ARG api_tz
ENV TZ ${api_tz}

ENTRYPOINT ["yarn", "watch"]
